type Query {
  categories: [Category]
  category(id: Int!): Category
}

type Mutation {
  CreateCategory(input: CategoryInput): Boolean
  UpdateCategory(id: Int!, input: CategoryInput): Boolean
  RemoveCategory(id: Int!): Boolean
}

type Category {
  id: Int
  category_name: String
}

input CategoryInput {
  id: Int
  category_name: String
}
